# docker-compose.yml (MODIFIED for Production with Docker Hub)
services:
  api:
    # Use the image from Docker Hub. Docker will pull it automatically.
    image: sparshsing96/documentation-agent-api:latest
    
    # Uncomment in local development.
    # image: documentation-agent-api
    # build: .
    
    container_name: documentation-agent-container
    ports:
      # Keep this bound to localhost for security (Nginx will proxy)
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    volumes:
      - ${DATA_HOST_PATH}:/app/processed_data
    restart: unless-stopped